// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWzYVHLIQxi5biLvgUr13ubohL_joejTA',
    appId: '1:979548281996:web:c8cf7a06d772a3a3832fa9',
    messagingSenderId: '979548281996',
    projectId: 'finalproject-eb873',
    authDomain: 'finalproject-eb873.firebaseapp.com',
    storageBucket: 'finalproject-eb873.firebasestorage.app',
    measurementId: 'G-DZKNGYP5RB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLNoWzilvJJixTaK3-IrkIFkI8hPVHXcI',
    appId: '1:979548281996:android:357994dd48a38a68832fa9',
    messagingSenderId: '979548281996',
    projectId: 'finalproject-eb873',
    storageBucket: 'finalproject-eb873.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDnN0Km9HMc2D2jl9IWuKGztaT8LW5-V0',
    appId: '1:979548281996:ios:6f2db49c3cfe1527832fa9',
    messagingSenderId: '979548281996',
    projectId: 'finalproject-eb873',
    storageBucket: 'finalproject-eb873.firebasestorage.app',
    iosBundleId: 'com.example.bitirmeProjesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDnN0Km9HMc2D2jl9IWuKGztaT8LW5-V0',
    appId: '1:979548281996:ios:6f2db49c3cfe1527832fa9',
    messagingSenderId: '979548281996',
    projectId: 'finalproject-eb873',
    storageBucket: 'finalproject-eb873.firebasestorage.app',
    iosBundleId: 'com.example.bitirmeProjesi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWzYVHLIQxi5biLvgUr13ubohL_joejTA',
    appId: '1:979548281996:web:08f1941e1f0a72ee832fa9',
    messagingSenderId: '979548281996',
    projectId: 'finalproject-eb873',
    authDomain: 'finalproject-eb873.firebaseapp.com',
    storageBucket: 'finalproject-eb873.firebasestorage.app',
    measurementId: 'G-77649C674C',
  );
}
